apiVersion: v1
kind: Template
metadata:
  name: java-dev-env
  annotations:
    openshift.io/display-name: Java Application DEV
    iconClass: fa fa-code
    description: Template to generate Java Develop Environment
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: ${PARAM_APP_NAME}
    name: ${PARAM_APP_NAME}
- apiVersion: v1
  kind: BuildConfig
  metadata:     
    labels:
      app: ${PARAM_APP_NAME}
    name: ${PARAM_APP_NAME}
  spec:
    runPolicy: Serial     
    source:
      type: Git
      git:
        ref: ${PARAM_GIT_BRANCH}
        uri: ${PARAM_GIT_REPO}
      contextDir: /
    strategy: 
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: redhat-openjdk18-openshift:1.2
          namespace: openshift
    output: 
      to:
        kind: ImageStreamTag
        name: ${PARAM_APP_NAME}:latest
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: ${PARAM_APP_NAME}
    name: ${PARAM_APP_NAME}
  spec:
    selector:
      deploymentConfig: ${PARAM_APP_NAME}
    template: 
      metadata:
        labels:
          deploymentConfig: ${PARAM_APP_NAME}
          name: ${PARAM_APP_NAME}
      spec:
        containers:
          - name: ${PARAM_APP_NAME}
            env:
              - name: TZ
                value: America/Santiago
              - name: LANG_FILE
                value: hello.es
            image: ${PARAM_APP_NAME}:latest
            ports:
              - containerPort: 8080
                protocol: TCP
            readinessProbe:
              failureThreshold: 3
              httpGet:
                path: /rest/hello
                port: 8080
                scheme: HTTP
              initialDelaySeconds: 60
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 20
            livenessProbe:
              failureThreshold: 3
              httpGet:
                path: /rest/hello
                port: 8080
                scheme: HTTP
              initialDelaySeconds: 120
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 20
            resources:
              limits:
                cpu: 500m
                memory: 300Mi
              requests:
                cpu: 500m
                memory: 300Mi
    triggers: 
    - type: "ImageChange"
      imageChangeParams:
        automatic: true
        containerNames:
        - ${PARAM_APP_NAME}
        from:
          kind: ImageStreamTag
          name: ${PARAM_APP_NAME}:latest
    replicas: 1 
    strategy: 
      type: Rolling
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ${PARAM_APP_NAME}
    name: ${PARAM_APP_NAME}
  spec:
    ports:
      - port: 8080
        protocol: TCP
        targetPort: 8080
    selector:
      deploymentConfig: ${PARAM_APP_NAME}
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Route
  metadata:
    name: ${PARAM_APP_NAME}
    labels:
      application: ${PARAM_APP_NAME}
  spec:
    to:
      kind: Service
      name: ${APPLICATION_NAME}

- kind: ConfigMap
  apiVersion: v1
  metadata:
    labels:
      app: ${PARAM_APP_NAME}
    name: ${PARAM_APP_NAME}
  data:
    hello.es: Hola desde OpenShift!
    hello.en: Hello from OpenShift!
parameters:
- description: The application name
  displayName: Application name
  name: PARAM_APP_NAME
  value: hello
  required: true
- description: The image name
  displayName: Image name
  name: PARAM_IMAGE_NAME
  value: hello
  required: false
- name: SOURCE_REPOSITORY_URL 
  displayName: Source Repository URL 
  description: The URL of the repository with your application source code 
  required: true
- name: SOURCE_REPOSITORY_REF
  displayName: Source Repository REF
  value: dev
  required: true
- name: CONTEXT_DIR
  value: /
  required: false
- name: SOURCE_BRANCH
  displayName: Source Branch
  value: dev
  required: true
- name: APP_NAME
  value: ${PARAM_APP_NAME}
- name: IMAGE_NAME
  value: ${PARAM_IMAGE_NAME}
- name: APP_TEMPLATE_FILE
  value: ${PARAM_APP_TEMPLATE_FILE}
- name: GIT_REPO
  value: ${PARAM_GIT_REPO}
- name: GIT_BRANCH
  value: ${PARAM_GIT_BRANCH}
- name: TAG_VERSION
  value: ${PARAM_TAG_VERSION}
- name: GIT_SECRET
  value: git-secret  
- name: BASE_IMAGE
  value: redhat-openjdk18-openshift:1.2
- name: ARTIFACTS_DIR
  value: ./target
- name: JENKINS_AGENT
  value: maven
- name: COMPILE_COMMAND
  value: "mvn package -DskipTests"
- name: TEST_COMMAND
  value: "mvn test"
- name: CODE_ANALYSIS_COMMAND
  value: none
- name: RELEASE_COMMAND
  value: none
- name: TECH
  value: java
